IF OBJECT_ID('TodoItems', 'U') IS NOT NULL
BEGIN
    DROP Table ToDoItems
END

CREATE TABLE ToDoItems
(
    Id INT NOT NULL IDENTITY(1, 1),
    Title NVARCHAR(256) NOT NULL,
    Details NVARCHAR(1024) NULL,
    CONSTRAINT [PK_ToDoItems_Id] PRIMARY KEY CLUSTERED ([ID] ASC)
)